title:            Damian Liu
description:      Damian's home page on the World Wide Web.
url:              https://yanl.cc

permalink:        pretty
timezone:         Asia/Shanghai
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "damian"
  -
    scope:
      path: "images/*.*"
    values:
      image: true
